# Generated by Django 5.2.8 on 2026-01-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='waveform_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='waveform_version',
            field=models.CharField(default='1.0', max_length=10),
        ),
    ]
