# Generated by Django 5.2.8 on 2026-01-15 18:17

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_track_waveform_generated_track_waveform_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Время прочтения')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], max_length=10, verbose_name='Уровень')),
                ('module', models.CharField(choices=[('auth', 'Аутентификация'), ('upload', 'Загрузка'), ('waveform', 'Waveform генерация'), ('api', 'API'), ('moderation', 'Модерация'), ('payment', 'Платежи'), ('system', 'Система')], max_length=20, verbose_name='Модуль')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Детали')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
            ],
            options={
                'verbose_name': 'Системный лог',
                'verbose_name_plural': 'Системные логи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('plays', models.IntegerField(default=0, verbose_name='Прослушивания')),
                ('likes', models.IntegerField(default=0, verbose_name='Лайки')),
                ('reposts', models.IntegerField(default=0, verbose_name='Репосты')),
                ('comments', models.IntegerField(default=0, verbose_name='Комментарии')),
                ('downloads', models.IntegerField(default=0, verbose_name='Скачивания')),
                ('shares', models.IntegerField(default=0, verbose_name='Шаринги')),
            ],
            options={
                'verbose_name': 'Аналитика трека',
                'verbose_name_plural': 'Аналитика треков',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WaveformGenerationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '⏳ Ожидание'), ('processing', '⚙️ Обработка'), ('completed', '✅ Завершено'), ('failed', '❌ Ошибка'), ('cancelled', '🚫 Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Время начала')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('attempt_count', models.IntegerField(default=0, verbose_name='Количество попыток')),
                ('points_generated', models.IntegerField(default=0, verbose_name='Сгенерировано точек')),
                ('processing_time', models.FloatField(default=0, verbose_name='Время обработки (сек)')),
            ],
            options={
                'verbose_name': 'Задача генерации waveform',
                'verbose_name_plural': 'Задачи генерации waveform',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='commentlike',
            options={'ordering': ['-created_at'], 'verbose_name': 'Лайк комментария', 'verbose_name_plural': 'Лайки комментариев'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='dailystats',
            options={'ordering': ['-date'], 'verbose_name': 'Дневная статистика', 'verbose_name_plural': 'Дневная статистика'},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['-created_at'], 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='hashtag',
            options={'ordering': ['-usage_count'], 'verbose_name': 'Хештег', 'verbose_name_plural': 'Хештеги'},
        ),
        migrations.AlterModelOptions(
            name='listeninghistory',
            options={'ordering': ['-listened_at'], 'verbose_name': 'История прослушивания', 'verbose_name_plural': 'История прослушиваний'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AlterModelOptions(
            name='passwordresettoken',
            options={'ordering': ['-created_at'], 'verbose_name': 'Токен сброса пароля', 'verbose_name_plural': 'Токены сброса пароля'},
        ),
        migrations.AlterModelOptions(
            name='playhistory',
            options={'ordering': ['-played_at'], 'verbose_name': 'История прослушиваний', 'verbose_name_plural': 'История прослушиваний'},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['-created_at'], 'verbose_name': 'Плейлист', 'verbose_name_plural': 'Плейлисты'},
        ),
        migrations.AlterModelOptions(
            name='playlisttrack',
            options={'ordering': ['position', '-added_at'], 'verbose_name': 'Трек в плейлисте', 'verbose_name_plural': 'Треки в плейлистах'},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['-created_at'], 'verbose_name': 'Трек', 'verbose_name_plural': 'Треки'},
        ),
        migrations.AlterModelOptions(
            name='trackcomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Комментарий к треку', 'verbose_name_plural': 'Комментарии к трекам'},
        ),
        migrations.AlterModelOptions(
            name='tracklike',
            options={'ordering': ['-liked_at'], 'verbose_name': 'Лайк трека', 'verbose_name_plural': 'Лайки треков'},
        ),
        migrations.AlterModelOptions(
            name='trackrepost',
            options={'ordering': ['-reposted_at'], 'verbose_name': 'Репост трека', 'verbose_name_plural': 'Репосты треков'},
        ),
        migrations.AlterModelOptions(
            name='usersession',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сессия пользователя', 'verbose_name_plural': 'Сессии пользователей'},
        ),
        migrations.AlterModelOptions(
            name='usertrackinteraction',
            options={'verbose_name': 'Взаимодействие с треком', 'verbose_name_plural': 'Взаимодействия с треками'},
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='is_public',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_artist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_pro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='playlists_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pro_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='soundcloud',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='total_comments',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего комментариев'),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='total_uploads',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего загрузок'),
        ),
        migrations.AddField(
            model_name='follow',
            name='notifications_enabled',
            field=models.BooleanField(default=True, verbose_name='Уведомления включены'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.playlist', verbose_name='Связанный плейлист'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='playhistory',
            name='duration_listened',
            field=models.PositiveIntegerField(default=0, verbose_name='Прослушано (секунд)'),
        ),
        migrations.AddField(
            model_name='playhistory',
            name='is_full_play',
            field=models.BooleanField(default=False, verbose_name='Полное прослушивание'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='is_collaborative',
            field=models.BooleanField(default=False, verbose_name='Коллаборативный'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Рекомендуемый'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='play_count',
            field=models.IntegerField(default=0, verbose_name='Количество прослушиваний'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='visibility',
            field=models.CharField(choices=[('public', '🌍 Публичный'), ('private', '🔒 Приватный'), ('unlisted', '🔗 Ссылочный')], default='public', max_length=20, verbose_name='Видимость'),
        ),
        migrations.AddField(
            model_name='track',
            name='bitrate',
            field=models.PositiveIntegerField(default=0, verbose_name='Битрейт (kbps)'),
        ),
        migrations.AddField(
            model_name='track',
            name='bpm',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='BPM (темп)'),
        ),
        migrations.AddField(
            model_name='track',
            name='download_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество скачиваний'),
        ),
        migrations.AddField(
            model_name='track',
            name='file_size',
            field=models.PositiveIntegerField(default=0, verbose_name='Размер файла (байт)'),
        ),
        migrations.AddField(
            model_name='track',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Рекомендуемый трек'),
        ),
        migrations.AddField(
            model_name='track',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Премиум контент'),
        ),
        migrations.AddField(
            model_name='track',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Виден только вам и указанным пользователям', verbose_name='Приватный трек'),
        ),
        migrations.AddField(
            model_name='track',
            name='key',
            field=models.CharField(blank=True, help_text='Музыкальная тональность (например: Cm, G#maj)', max_length=10, null=True, verbose_name='Тональность'),
        ),
        migrations.AddField(
            model_name='track',
            name='license',
            field=models.CharField(default='All rights reserved', help_text='Права на использование трека', max_length=100, verbose_name='Лицензия'),
        ),
        migrations.AddField(
            model_name='track',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Место записи'),
        ),
        migrations.AddField(
            model_name='track',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата модерации'),
        ),
        migrations.AddField(
            model_name='track',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_tracks', to=settings.AUTH_USER_MODEL, verbose_name='Проверено модератором'),
        ),
        migrations.AddField(
            model_name='track',
            name='moderation_notes',
            field=models.TextField(blank=True, verbose_name='Заметки модератора'),
        ),
        migrations.AddField(
            model_name='track',
            name='recording_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата записи'),
        ),
        migrations.AddField(
            model_name='track',
            name='sample_rate',
            field=models.PositiveIntegerField(default=0, verbose_name='Частота дискретизации (Hz)'),
        ),
        migrations.AddField(
            model_name='track',
            name='share_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество шарингов'),
        ),
        migrations.AddField(
            model_name='track',
            name='tags',
            field=models.TextField(blank=True, help_text='Теги через запятую (альтернатива хештегам)', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='track',
            name='waveform_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата генерации waveform'),
        ),
        migrations.AddField(
            model_name='track',
            name='waveform_points',
            field=models.PositiveIntegerField(default=120, verbose_name='Количество точек waveform'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usertrackinteraction',
            name='played',
            field=models.BooleanField(default=False, verbose_name='Прослушан'),
        ),
        migrations.AddField(
            model_name='usertrackinteraction',
            name='played_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время прослушивания'),
        ),
        migrations.AddField(
            model_name='usertrackinteraction',
            name='saved',
            field=models.BooleanField(default=False, verbose_name='Сохранено'),
        ),
        migrations.AddField(
            model_name='usertrackinteraction',
            name='saved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время сохранения'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество лайков'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.comment', verbose_name='Родительский комментарий'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.track', verbose_name='Трек'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.comment', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата лайка'),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='dailystats',
            name='date',
            field=models.DateField(unique=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='dailystats',
            name='total_likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего лайков'),
        ),
        migrations.AlterField(
            model_name='dailystats',
            name='total_plays',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего прослушиваний'),
        ),
        migrations.AlterField(
            model_name='dailystats',
            name='total_reposts',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего репостов'),
        ),
        migrations.AlterField(
            model_name='dailystats',
            name='total_tracks',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего треков'),
        ),
        migrations.AlterField(
            model_name='dailystats',
            name='total_users',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего пользователей'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='На кого подписан'),
        ),
        migrations.AlterField(
            model_name='listeninghistory',
            name='listened_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время прослушивания'),
        ),
        migrations.AlterField(
            model_name='listeninghistory',
            name='play_count',
            field=models.IntegerField(default=1, verbose_name='Количество прослушиваний'),
        ),
        migrations.AlterField(
            model_name='listeninghistory',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.track', verbose_name='Трек'),
        ),
        migrations.AlterField(
            model_name='listeninghistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.trackcomment', verbose_name='Связанный комментарий'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.track', verbose_name='Связанный трек'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Связанный пользователь'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('follow', 'Новая подписка'), ('like', 'Лайк'), ('repost', 'Репост'), ('comment', 'Комментарий'), ('mention', 'Упоминание'), ('new_track', 'Новый трек'), ('playlist_add', 'Добавление в плейлист'), ('system', 'Системное'), ('waveform_ready', 'Waveform готов')], max_length=20, verbose_name='Тип уведомления'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='playhistory',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес'),
        ),
        migrations.AlterField(
            model_name='playhistory',
            name='played_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время прослушивания'),
        ),
        migrations.AlterField(
            model_name='playhistory',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_history', to='api.track', verbose_name='Трек'),
        ),
        migrations.AlterField(
            model_name='playhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_history', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='playhistory',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='cover',
            field=models.ImageField(blank=True, null=True, storage=api.models.OverwriteStorage(), upload_to=api.models.playlist_cover_path, verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='cover_url',
            field=models.URLField(blank=True, default='', verbose_name='Ссылка на обложку'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='likes_count',
            field=models.IntegerField(default=0, verbose_name='Количество лайков'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название плейлиста'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(related_name='playlists', through='api.PlaylistTrack', to='api.track', verbose_name='Треки'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='playlisttrack',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='playlisttrack',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='playlisttrack',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.playlist', verbose_name='Плейлист'),
        ),
        migrations.AlterField(
            model_name='playlisttrack',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='playlisttrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.track', verbose_name='Трек'),
        ),
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.CharField(help_text='Имя исполнителя или группы', max_length=255, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(default='', help_text='Поддерживаемые форматы: MP3, WAV, OGG, FLAC, M4A', max_length=500, storage=api.models.OverwriteStorage(), upload_to=api.models.track_audio_path, verbose_name='Аудио файл'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_url',
            field=models.URLField(blank=True, default='', help_text='Внешняя ссылка на аудио (если нет файла)', verbose_name='Ссылка на аудио'),
        ),
        migrations.AlterField(
            model_name='track',
            name='comment_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество комментариев'),
        ),
        migrations.AlterField(
            model_name='track',
            name='cover',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер: 1000x1000px', null=True, storage=api.models.OverwriteStorage(), upload_to=api.models.track_cover_path, verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='track',
            name='cover_url',
            field=models.URLField(blank=True, default='', help_text='Внешняя ссылка на обложку', verbose_name='Ссылка на обложку'),
        ),
        migrations.AlterField(
            model_name='track',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='track',
            name='description',
            field=models.TextField(blank=True, help_text='Расскажите о вашем треке', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.CharField(default='0:00', help_text='Длительность трека (например: 3:45)', max_length=10, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='track',
            name='genre',
            field=models.CharField(choices=[('rock', '🎸 Рок'), ('pop', '🎤 Поп'), ('hiphop', '🎧 Хип-хоп'), ('electronic', '🎹 Электроника'), ('jazz', '🎷 Джаз'), ('classical', '🎻 Классика'), ('metal', '🤘 Метал'), ('indie', '🎵 Инди'), ('lofi', '☕ Lo-Fi'), ('ambient', '🌌 Эмбиент'), ('folk', '🌿 Фолк'), ('blues', '🎶 Блюз'), ('reggae', '🌈 Регги'), ('punk', '⚡ Панк'), ('dance', '💃 Танцевальная'), ('experimental', '🔬 Экспериментальная'), ('other', '🎼 Другое')], default='other', max_length=50, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='track',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='tracks', to='api.hashtag', verbose_name='Хештеги'),
        ),
        migrations.AlterField(
            model_name='track',
            name='is_downloadable',
            field=models.BooleanField(default=True, verbose_name='Доступно для скачивания'),
        ),
        migrations.AlterField(
            model_name='track',
            name='is_explicit',
            field=models.BooleanField(default=False, help_text='Содержит нецензурную лексику или взрослый контент', verbose_name='Эксплицитный контент'),
        ),
        migrations.AlterField(
            model_name='track',
            name='like_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество лайков'),
        ),
        migrations.AlterField(
            model_name='track',
            name='play_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество прослушиваний'),
        ),
        migrations.AlterField(
            model_name='track',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='track',
            name='repost_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество репостов'),
        ),
        migrations.AlterField(
            model_name='track',
            name='status',
            field=models.CharField(choices=[('draft', '📝 Черновик'), ('pending', '⏳ На модерации'), ('published', '✅ Опубликован'), ('rejected', '❌ Отклонен'), ('archived', '🗄️ В архиве')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(help_text='Укажите название вашего трека', max_length=255, verbose_name='Название трека'),
        ),
        migrations.AlterField(
            model_name='track',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='track',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_tracks', to=settings.AUTH_USER_MODEL, verbose_name='Загружено пользователем'),
        ),
        migrations.AlterField(
            model_name='track',
            name='waveform_data',
            field=models.JSONField(blank=True, default=list, help_text='Массив чисел 0-100 для отрисовки waveform', verbose_name='Waveform данные'),
        ),
        migrations.AlterField(
            model_name='track',
            name='waveform_generated',
            field=models.BooleanField(default=False, verbose_name='Waveform сгенерирован'),
        ),
        migrations.AlterField(
            model_name='track',
            name='waveform_version',
            field=models.CharField(default='1.0', max_length=10, verbose_name='Версия waveform'),
        ),
        migrations.AlterField(
            model_name='trackcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='trackcomment',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
        migrations.AlterField(
            model_name='trackcomment',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='Количество лайков'),
        ),
        migrations.AlterField(
            model_name='trackcomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_track_comments', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
        migrations.AlterField(
            model_name='trackcomment',
            name='text',
            field=models.TextField(verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='trackcomment',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_comments', to='api.track', verbose_name='Трек'),
        ),
        migrations.AlterField(
            model_name='trackcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='trackcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_comments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='tracklike',
            name='liked_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время лайка'),
        ),
        migrations.AlterField(
            model_name='tracklike',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.track', verbose_name='Трек'),
        ),
        migrations.AlterField(
            model_name='tracklike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_likes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='trackrepost',
            name='comment',
            field=models.TextField(blank=True, help_text='Комментарий к репосту', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='trackrepost',
            name='reposted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата репоста'),
        ),
        migrations.AlterField(
            model_name='trackrepost',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to='api.track', verbose_name='Трек'),
        ),
        migrations.AlterField(
            model_name='trackrepost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='usertrackinteraction',
            name='liked',
            field=models.BooleanField(default=False, verbose_name='Лайк'),
        ),
        migrations.AlterField(
            model_name='usertrackinteraction',
            name='liked_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время лайка'),
        ),
        migrations.AlterField(
            model_name='usertrackinteraction',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.track', verbose_name='Трек'),
        ),
        migrations.AlterField(
            model_name='usertrackinteraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='playhistory',
            index=models.Index(fields=['track', 'played_at'], name='api_playhis_track_i_3899d0_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['genre', 'status'], name='api_track_genre_ebbb40_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['like_count', 'play_count'], name='api_track_like_co_0804fb_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['created_at'], name='api_track_created_2818ad_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['title'], name='api_track_title_1d65fe_idx'),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='trackanalytics',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='api.track', verbose_name='Трек'),
        ),
        migrations.AddField(
            model_name='waveformgenerationtask',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waveform_tasks', to='api.track', verbose_name='Трек'),
        ),
        migrations.AlterUniqueTogether(
            name='trackanalytics',
            unique_together={('track', 'date')},
        ),
    ]
