# Generated by Django 5.2.8 on 2026-01-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_message_systemlog_trackanalytics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='Длительность в секундах'),
        ),
    ]
