# Generated by Django 5.2.8 on 2026-01-17 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_track_duration_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.trackcomment', verbose_name='Родительский комментарий'),
        ),
        migrations.AlterField(
            model_name='trackcomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_track_comments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, поставившие лайк'),
        ),
    ]
