# Generated by Django 5.2.8 on 2026-01-22 15:22

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_trackcomment_parent_alter_trackcomment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='header_dominant_color',
            field=models.CharField(default='#7c3aed', help_text='Доминирующий цвет header image (формат #RRGGBB)', max_length=7, verbose_name='Dominant Color'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='header_image',
            field=models.ImageField(blank=True, help_text='Header image для профиля (рекомендуется 1500x500px)', null=True, storage=api.models.OverwriteStorage(), upload_to=api.models.user_header_path, verbose_name='Header Image'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='header_image_url',
            field=models.URLField(blank=True, default='', help_text='Внешняя ссылка на header image', verbose_name='Header Image URL'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='header_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Header Updated At'),
        ),
    ]
