# Generated by Django 5.2.8 on 2026-01-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customuser_header_dominant_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gridscan_color',
            field=models.CharField(default='#003196', help_text='Цвет GridScan (формат #RRGGBB)', max_length=7, verbose_name='GridScan Color'),
        ),
    ]
