# Generated by Django 5.2.8 on 2026-01-22 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customuser_gridscan_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='header_dominant_color',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='header_image_url',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Дополнительный профиль',
                'verbose_name_plural': 'Дополнительные профили',
            },
        ),
    ]
