# Generated by Django 5.2.8 on 2026-01-23 17:20

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_customuser_header_dominant_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_url',
            field=models.URLField(blank=True, default='', help_text='Внешняя ссылка на аватар (если не загружен файл)', verbose_name='Внешний URL аватара'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Аватар пользователя (рекомендуется 200x200px)', null=True, storage=api.models.OverwriteStorage(), upload_to=api.models.avatar_upload_path, verbose_name='Аватар'),
        ),
    ]
