# Generated by Django 5.2.8 on 2026-02-05 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_customuser_avatar_url_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listeninghistory',
            options={'ordering': ['-listened_at'], 'verbose_name': 'Уникальное прослушивание', 'verbose_name_plural': 'Уникальные прослушивания'},
        ),
        migrations.AlterModelOptions(
            name='playhistory',
            options={'ordering': ['-played_at'], 'verbose_name': 'Детальная история прослушивания', 'verbose_name_plural': 'Детальная история прослушиваний'},
        ),
        migrations.AlterUniqueTogether(
            name='playhistory',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='listeninghistory',
            name='play_count',
        ),
        migrations.AddField(
            model_name='listeninghistory',
            name='is_counted',
            field=models.BooleanField(default=True, verbose_name='Учтено в статистике'),
        ),
        migrations.AddField(
            model_name='listeninghistory',
            name='listened_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='Прослушано секунд'),
        ),
        migrations.AlterField(
            model_name='listeninghistory',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_history', to='api.track', verbose_name='Трек'),
        ),
        migrations.AlterField(
            model_name='listeninghistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_history', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='listeninghistory',
            index=models.Index(fields=['user', 'listened_at'], name='api_listeni_user_id_b6c25c_idx'),
        ),
        migrations.AddIndex(
            model_name='listeninghistory',
            index=models.Index(fields=['track', 'listened_at'], name='api_listeni_track_i_106783_idx'),
        ),
        migrations.AddIndex(
            model_name='listeninghistory',
            index=models.Index(fields=['user', 'track'], name='api_listeni_user_id_35ec48_idx'),
        ),
    ]
