# Generated by Django 5.2.8 on 2026-02-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_listeninghistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, default='', help_text='Страна проживания пользователя', max_length=100, verbose_name='Страна'),
        ),
    ]
