# Generated by Django 5.2.8 on 2026-02-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_customuser_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='_duration_calculated',
            field=models.BooleanField(default=False, editable=False, verbose_name='Длительность вычислена'),
        ),
    ]
