# Generated by Django 5.2.8 on 2026-02-16 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_track__duration_calculated'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата лайка')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.playlist', verbose_name='Плейлист')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_playlists', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лайк плейлиста',
                'verbose_name_plural': 'Лайки плейлистов',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'playlist')},
            },
        ),
        migrations.CreateModel(
            name='PlaylistRepost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата репоста')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to='api.playlist', verbose_name='Плейлист')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reposted_playlists', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Репост плейлиста',
                'verbose_name_plural': 'Репосты плейлистов',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'playlist')},
            },
        ),
    ]
