# Generated by Django 5.2.8 on 2026-02-19 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_playlistlike_playlistrepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='now_playing_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Обновлено сейчас слушает'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='now_playing_is_playing',
            field=models.BooleanField(default=False, verbose_name='Сейчас играет'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='now_playing_track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='now_playing_users', to='api.track', verbose_name='Сейчас слушает трек'),
        ),
    ]
