# Generated by Django 5.2.8 on 2026-02-19 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_message_options_remove_message_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DialogState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Скрыт из списка')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='api.conversation', verbose_name='Диалог')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialog_states', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Состояние диалога',
                'verbose_name_plural': 'Состояния диалогов',
                'indexes': [models.Index(fields=['user', 'is_hidden'], name='api_dialogs_user_id_ac43c1_idx'), models.Index(fields=['conversation', 'user'], name='api_dialogs_convers_16f03b_idx')],
                'unique_together': {('user', 'conversation')},
            },
        ),
    ]
