# Generated by Django 5.2.8 on 2026-02-20 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_dialogstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogstate',
            name='last_read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последнего прочтения'),
        ),
        migrations.AddField(
            model_name='dialogstate',
            name='last_read_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.message', verbose_name='Последнее прочитанное сообщение'),
        ),
        migrations.AddIndex(
            model_name='dialogstate',
            index=models.Index(fields=['user', 'last_read_at'], name='api_dialogs_user_id_e8316f_idx'),
        ),
    ]
