# Generated by Django 5.2.8 on 2026-02-21 09:57

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_dialogstate_last_read_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to=api.models.voice_message_path, verbose_name='Голосовое сообщение'),
        ),
        migrations.AddField(
            model_name='message',
            name='voice_duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность голосового сообщения (сек)'),
        ),
        migrations.AddField(
            model_name='message',
            name='waveform',
            field=models.JSONField(blank=True, null=True, verbose_name='Waveform данные для голосового сообщения'),
        ),
    ]
