# Generated by Django 5.2.8 on 2026-02-21 13:45

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_message_voice_message_voice_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.message_image_path, verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='message',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=api.models.message_video_path, verbose_name='Видео'),
        ),
    ]
