# Generated by Django 5.2.8 on 2026-02-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_message_image_message_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reactions',
            field=models.JSONField(blank=True, default=dict, help_text='Формат: {"❤️": [1,5], "😂": [2]} - список user_id кто поставил', verbose_name='Реакции на сообщение'),
        ),
    ]
