# Generated by Django 5.2.8 on 2026-02-22 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_message_reactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('followers', models.PositiveIntegerField(default=0, verbose_name='Подписчики')),
                ('following', models.PositiveIntegerField(default=0, verbose_name='Подписки')),
                ('tracks', models.PositiveIntegerField(default=0, verbose_name='Треки')),
                ('total_listens', models.PositiveIntegerField(default=0, verbose_name='Всего прослушиваний')),
                ('total_likes', models.PositiveIntegerField(default=0, verbose_name='Всего лайков')),
                ('total_reposts', models.PositiveIntegerField(default=0, verbose_name='Всего репостов')),
                ('total_comments', models.PositiveIntegerField(default=0, verbose_name='Всего комментариев')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Дневная статистика пользователя',
                'verbose_name_plural': 'Дневная статистика пользователей',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='api_userdai_user_id_46bf67_idx'), models.Index(fields=['date'], name='api_userdai_date_efd2cd_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
