# Generated by Django 5.2.8 on 2026-02-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_customuser_ban_created_at_customuser_ban_reason_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banappeal',
            options={'ordering': ['-created_at'], 'verbose_name': 'Апелляция бана', 'verbose_name_plural': 'Апелляции банов'},
        ),
        migrations.RenameField(
            model_name='banappeal',
            old_name='admin_note',
            new_name='admin_comment',
        ),
        migrations.RenameField(
            model_name='banappeal',
            old_name='message',
            new_name='disagree_text',
        ),
        migrations.AddField(
            model_name='banappeal',
            name='ban_reason_snapshot',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='banappeal',
            name='ban_until_snapshot',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='banappeal',
            name='banned_by_snapshot',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='banappeal',
            name='username_snapshot',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='banappeal',
            name='status',
            field=models.CharField(choices=[('pending', '⏳ Pending'), ('reviewed', '✅ Reviewed'), ('rejected', '❌ Rejected')], default='pending', max_length=20),
        ),
    ]
