# Generated by Django 5.2.8 on 2026-02-25 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_userreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='admin_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userreport',
            name='ban_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userreport',
            name='ban_permanent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userreport',
            name='ban_reason_admin',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userreport',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userreport',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_decided', to=settings.AUTH_USER_MODEL),
        ),
    ]
