# Generated by Django 5.2.8 on 2026-02-25 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_userreport_admin_comment_userreport_ban_days_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userreport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Репорт', 'verbose_name_plural': 'Репорты'},
        ),
        migrations.RenameField(
            model_name='userreport',
            old_name='admin_comment',
            new_name='admin_response',
        ),
        migrations.RenameField(
            model_name='userreport',
            old_name='ban_reason_admin',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='userreport',
            name='ban_days',
        ),
        migrations.RemoveField(
            model_name='userreport',
            name='ban_permanent',
        ),
        migrations.RemoveField(
            model_name='userreport',
            name='decided_at',
        ),
        migrations.RemoveField(
            model_name='userreport',
            name='decided_by',
        ),
        migrations.RemoveField(
            model_name='userreport',
            name='reported_user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='status_text',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='userreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userreport',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('ban', 'Ban'), ('unban', 'Unban'), ('warning', 'Warning'), ('mute', 'Mute')], max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Модерационное действие',
                'verbose_name_plural': 'Модерационные действия',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_response', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals', to='api.moderationaction')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals_responded', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Апелляция',
                'verbose_name_plural': 'Апелляции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserReportOld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_comment', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('ban_reason_admin', models.TextField(blank=True, default='')),
                ('ban_days', models.IntegerField(blank=True, null=True)),
                ('ban_permanent', models.BooleanField(default=False)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_decided_old', to=settings.AUTH_USER_MODEL)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received_old', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_sent_old', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
