# Generated by Django 5.2.8 on 2026-02-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_userreport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='presence_mode',
            field=models.CharField(blank=True, choices=[('auto', 'Auto'), ('online', 'Online'), ('afk', 'AFK'), ('dnd', 'Do Not Disturb'), ('offline', 'Offline')], default='auto', help_text='Ручной режим присутствия: auto (авто), online (всегда онлайн), afk (отошел), dnd (не беспокоить), offline (всегда оффлайн)', max_length=10, verbose_name='Режим присутствия'),
        ),
    ]
