# Generated by Django 5.2.8 on 2026-02-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_customuser_presence_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='banappeal',
            name='ai_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='banappeal',
            name='ai_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banappeal',
            name='ai_model',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='banappeal',
            name='ai_recommendation',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='banappeal',
            name='ai_risk',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='banappeal',
            name='ai_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='banappeal',
            name='ai_summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
